### ISSUE TITLE
Question about multi-inputs ...

### ISSUE THREAD

**Issue by Rhysmann** [juliagoda/antimicroX#117]
Antimicro works great with my CH Products Fighterstick in Rising Storm 2 Vietnam.

Couple issues:
However there is no 4th axis to assign the rudder pedal to for yawing.
Is there a way that I don't know about?
For now I am using a hat switch for yawing.

Also when using Antimicro for Battlefield 4 I cannot get into any server.
Stupid message like 'cannot join server'.
Seems that BF4/Origin do not allow the use of this program. Am I wrong?

Any help would be greatly appreciated.

Whoever created this program is a genius!

I have not been able to get any other utility progam to work at all in any game.

Using Windows 10 Prof 64 bit.

**Comment by juliagoda** [comment]
No, I didn't create the program, it was Ryochan7, but even he starred my fork. Anyway I see that you are using Windows... Well, so you are using the version from AntiMicro project, not my antimicroX fork. I am sorry that I don't have support for Windows, but I don't have Windows at all. This is why. In the future I want to create support for other systems too. To be honest I don't know, how the old version works, because my fork has been changing all the time since I forked it.
