### ISSUE TITLE
Further Maintaining of AntiMicroX

### ISSUE THREAD

**Issue by pktiuk** [juliagoda/antimicroX#154]
First of all,  many thanks for @juliagoda  for maintaining this project until now, it is clear, she spent a lot of her free time to voluntarily revive and maintain previously abandoned project called AntiMicro, and reforged it into new AntiMicroX.

But now for maintaining continuity of this project I have created a new Github organization that would provide further maintenance for this project. I have already forked this and I would like to invite everyone interested in contributing to join this project.

New fork: https://github.com/AntiMicroX/antimicroX

**Comment by gombosg** [comment]
Thanks for stepping up as a maintainer for this great piece of software.
I'd be happy to help, but I have never touched C++ code. :slightly_smiling_face: 
Maybe this would be too deep waters for me to try it...?

Anyway, IMO the most important priorities now are
- triaging issues in this repo, transferring important ones to the new repo
- keep builds running for latest OSes
- keep fixing critical bugs
- making the software known because it's cool! This is where I can help, too :rofl:. Submitting to some places, lists etc. here and there.
- improve packaging. Get it packaged for more OSes. I'm a Fedora packager, maybe I can also make a Flatpak.
- keep shipping new tags/releases with these fixes
- once we see that this is working out, redirect people from this repo to the new one
- and, if possible and there is capacity for it, keep improving this neat app.

**Comment by pktiuk** [comment]
@gombosg 
Would you like to join and help with preparing new repository?

**Comment by gombosg** [comment]
Yes, let's do this!

**Comment by pktiuk** [comment]
I have added you. 
Could you deal with proper mirroring of this repo?

**Comment by gombosg** [comment]
Done, I just used the [official instructions](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository#mirroring-a-repository).
https://github.com/AntiMicroX/antimicroX2
You can delete the other one and rename this.
Now, [PRs haven't been mirrored](https://stackoverflow.com/a/34266401/8677156), that's why you got the error messages. You don't miss much because there were no open PRs.

**Comment by sirlucjan** [comment]
I don't want to be malicious, but I think you should remove the note that the program is no longer developed. I mean the newly created repo so that there is full clarity.

**Comment by pktiuk** [comment]
I will do it in the soon.

I would also like to ask to remove this note from this repository, because not project is abandoned, but just this repository.

**Comment by juliagoda** [comment]
> I would also like to ask to edit this note from this repository, because not entire project is abandoned, but just this repository

I can just add info in README about your site. I don't think it's good idea because people will create new issues here instead on your site. I want people to know that my participation is over, especially since you have no intention of adding new features to the program.

**Comment by pktiuk** [comment]
By editing i just meant changing word `project` to word `repository`  in the first sentence, but just giving a new url is also fine.
