### ISSUE TITLE
AntiMicro Disappears

### ISSUE THREAD

**Issue by Robertfm10** [juliagoda/antimicroX#88]
I am new to Antimicro. I have downloaded successfully and used quick set which worked fine. I saved the setting using simple save button.

The main panel disappeared. I tried to open it again but nothing happened. I do know that the panel is open because when I tried to uninstall that tool said I couldn't because a version was open.

Any help would be welcome.

**Comment by juliagoda** [comment]
Hello. 
1) Are you new to Antimicro or antimicroX? 
2) Where did you downloaded antimicro from? 
3) What is the version of your antimicro? From the last commit or some chosen version? 
4) What is your operating system?

**Comment by Robertfm10** [comment]
I downloaded latest version on Git Hub V 2.23 Windows 10. I have since
posting discovered it was open in Start up menu so I have now saved it to
Task Bar and it is working from there. I don't know why desktop short cut
didn't work.

Robert Feal-Martinez
35 Rosneath Castle Caravan Park
Rosneath
Helensburgh
G840QS
01436831455

**Comment by juliagoda** [comment]
The current version is 2.25. which the official AntiMicro group hasn't released (the last version is 2.23, my versions start with 2.24), I don't belong to this group because my program is heading in a different direction. I don't have support for Windows at the moment, but I plan to rewrite the old code to the new one and I want the program to work on Linux and on Windows and OSX in the near future.  I have nothing personally to do with the main AntiMicro group.
