### ISSUE TITLE
Feature request: Ability to bind F13-F24 by drop down menu

### ISSUE THREAD

**Issue by CalAlaera** [juliagoda/antimicroX#91]
These keycodes can't be typed by typical keyboards and would therefore be perfect for sole use by macros. As they can't be typed they would need to be added to the on screen clickable keyboard, perhaps under the "More" drop down menu?

Thanks :)

**Comment by juliagoda** [comment]
Ok, I will do it

**Comment by juliagoda** [comment]
I created a test for F13 and F14, but provided that there are really F13 and F14 buttons on the keyboard, otherwise X11 returns 0 for these buttons for "xkeysymtokeycode" and the buttons are not added to "Others" list - "The XKeycodeToKeysym function uses INTERNAL Xlib tables and returns the KeySym defined for the specified KeyCode and the element of the KeyCode vector. If the specified KeySym is not defined for any KeyCode, XKeysymToKeycode returns zero". Otherwise, I don't know if that will be possible.  The program maps the buttons from the keyboard to the gamepad. A button on the gamepad would end up trying to call a button on a keyboard that is physically not there. If I may know, in such case what would such a thing be needed for?
